#!/bin/bash
################################################################################
#
#   Test if a folder is a valid Dirvish vault
#
################################################################################

function synopsis {
	echo "Test if a given folder is a valid Dirvish vault."
}

function usage {
	echo "Usage: $0 /path/to/vault [-s/--silent]"
	echo "Where the path is excluding any trailing /-characters."
}
## -------------------------------------------------------------------------- ##
# Run params
SILENT="" # Non empty -> True
VAULT=''

## -------------------------------------------------------------------------- ##

## Parse input
SHORT_ARGS='sh'
LONG_ARGS='silent,help' # Comma separated

# We put the parsed options in a variable for now since we want to check getopts
# return value. Using getopt together with set would have removed the return val
options=$(getopt -o "$SHORT_ARGS" --long "$LONG_ARGS" -- "$@")

if [ $? -ne 0 ]; then
	echo 'getopt could not parse input. Terminating...' >&2
	exit 1
fi
eval set -- "$options" # Changing positional params to getopt filtered version of them.
unset options # We don't need the options any more.

# consume 1-2 positional params as flags at the time until there are no more.
while true
do
	case "$1" in
		'-s' | '--silent' )
			SILENT="True"
			shift
			continue
			;;
		'-h' | '--help' )
			synopsis
			usage
			shift
			exit
			;;
		'--') # End of flagged params
			shift
			break # Break while loop
			;; # Put here because it doesn't feel right to remove it
		*)
			echo "We shouldn't get here. Terminating ..." >&2
			exit 1
	esac
done
## -------------------------------------------------------------------------- ##
# Colors for prettier print
U='\033[0;0m'
R='\033[0;31m'
Y='\033[1;33m'
G='\033[0;32m'
B='\033[0;34m'
## -------------------------------------------------------------------------- ##
## Sanity checks
if [ $# -ne 1 ]; then
	echo -e "${R}Error:${U} Expected one vault directory as input." 1>&2
	usage 1>&2
	exit 8
else
	VAULT="$1"
	CONF="$VAULT/dirvish/default.conf"
fi

## -------------------------------------------------------------------------- ##
if [ -f "$CONF" ] ; then
	if [ -z "$SILENT" ] ; then
		echo "$VAULT is a valid vault."
	fi
	exit 0
else
	if [ -z "$SILENT" ] ; then
		echo "$VAULT is not a valid vault."
		echo "Missing: $CONF"
	fi
	exit 1
fi
